version: 2.1
jobs:
 build:
  working_directory: ~/public
  docker:      
      - image: cimg/openjdk:19.0.1
      - image: cimg/node:19.2.0
  steps:   
    - checkout
    - sleep_for_secs : 10
    - run:  
       name: update-npm
       command: npm install       
    - restore_cache:
       key: dependency-cache-{{ checksum "package.json" }}
    - run:
       name: install-npm-wee
       command: npm install
    - save_cache:
        paths:
          - "./node_modules"
        key:  dependency-cache-{{ checksum "package.json" }}
    - run: 
       name: test
       command: npm test
    - store_artifacts:
        path: test-results.xml
        #prefix: tests 
    - store_artifacts:
        path: coverage
       # prefix: coverage
    - store_test_results:
        path:  test-results.xml     
