version: 2.1
jobs:
 build:
  working_directory: ~/public
  docker:      
      - image: cimg/node:19.2.0
    #   - image: selenium/standalone-chrome
    #   - image: cimg/openjdk:11.0.16
  steps:   
    - checkout
   #  - run: java --version
    - run:  
       name: update-npm
       command: npm install       
    - restore_cache:
       key: dependency-cache-{{ checksum "package.json" }}
    - run:
       name: install-npm-wee
       command: npm install
    - save_cache:
        paths:
          - "./node_modules"
        key:  dependency-cache-{{ checksum "package.json" }}          
    - run: 
         name: docker compose
         command: cd sample
                  docker-compose up -d               
    - run: 
         name: test
         command: npm test
    - run: 
         name: docker compose
         command: docker-compose down -d
    - store_artifacts:
        path: test-results.xml
        #prefix: tests 
    - store_artifacts:
        path: coverage
       # prefix: coverage
    - store_test_results:
        path:  test-results.xml     
