version: 2.1
orbs:
  wait-for: cobli/wait-for@1.0.0
jobs:
 build:
  working_directory: ~/public
  docker:
      - image: cimg/node:19.2.0
      - image: cimg/openjdk:19.0.1
  steps:   
    - checkout
    - wait-for/openjdk
    - run:  
       name: update-npm
       command: npm install       
    - restore_cache:
       key: dependency-cache-{{ checksum "package.json" }}
    - run:
       name: install-npm-wee
       command: npm install
    - save_cache:
        paths:
          - "./node_modules"
        key:  dependency-cache-{{ checksum "package.json" }}
    - run: 
       name: test
       command: npm test
    - store_artifacts:
        path: test-results.xml
        #prefix: tests 
    - store_artifacts:
        path: coverage
       # prefix: coverage
    - store_test_results:
        path:  test-results.xml     
