version: 2.1
jobs:
 build:
 
  working_directory: ~/public
  docker:   
    #   - image: ubuntu-2204:2022.04.2   
      - image: cimg/node:15.0.1
      - image: cimg/base:2022.06      
        auth:
          username: sandeep.reddy@infobeans.com
          password: Sandeep@123
    #   - image: selenium/standalone-chrome
    #   - image: cimg/openjdk
  steps:     
    - checkout
   #  - run: java --version
    - setup_remote_docker:
          version: 20.10.14
    - run:  
       name: update-npm
       command: npm install       
    - restore_cache:
       key: dependency-cache-{{ checksum "package.json" }}
    - run:
       name: install-npm-wee
       command: npm install
    - save_cache:
        paths:
          - "./node_modules"
        key:  dependency-cache-{{ checksum "package.json" }}  
    - run: 
         name: test
         command: npm test            
    - run: 
         name: docker compose
         command: docker-compose up -d               
    - run: 
         name: test
         command: npm test
    # - run: 
    #      name: docker compose
    #      command: docker-compose down -d
    - store_artifacts:
        path: test-results.xml
        #prefix: tests 
    - store_artifacts:
        path: coverage
       # prefix: coverage
    - store_test_results:
        path:  test-results.xml     
